services:
  db:
    image: mysql:latest
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/init:/docker-entrypoint-initdb.d
      - ./mysql/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: nibble
      MYSQL_USER: nibble
      MYSQL_PASSWORD: nibble
  flyway:
    image: redgate/flyway
    command: -url=jdbc:mysql://db -schemas=nibble -user=root -password=root -connectRetries=60 migrate
    volumes:
      - ./flyway/migration:/flyway/sql
      - ./flyway/conf:/flyway/conf
    depends_on:
      - db