spring:
  datasource:
    url: jdbc:mysql://localhost:3306/nibble
    username: root
    password: root
logging:
  level:
    root: INFO
    io:
      github:
        tttol:
          nibble4j: DEBUG
    com:
      zaxxer:
        hikari:
          HikariDataSource: WARN
